### ISSUE TITLE
Can't build the game

### ISSUE THREAD

**Issue by freem-trg** [deepnight/ld41-nightclubShowdown#1]
First of all, thank you for sharing the game source code! The game looks perfect! You've made fantastic work due LD.
I've tried to build the game, but has problem with **mt.*** library. If I understand correctly, it is internal library you using in the Motion Tween. Is there any possibility to share or open the library? Or may be it is available via haxelib/github?

In any case, thanks for your work!

**Comment by deepnight** [comment]
Hi! Unfortunately, the mt.* package contains libs that haven't been released by my company Motion Twin for now. That's something we're discussing already, so I might push them on git one day, but I definitely can't promise :( 
The source code here is more for educational purpose (and because I always publish my Ludum Dare entries sources ^^)

**Comment by freem-trg** [comment]
Thank you for your reply!
I'm inspired by your LD games wanted to learn heaps by working example (unfortunately library has now good documentation and examples). May be it is possible to publish only used parts of the library (like it was DCEed :) ). But it is additional work for you... :(

I know how difficult it is to write articles/posts, but may be you have plans to write about tools/methodics, you used to hack LD games (castledb or tools for animations/shaders).

**Comment by deepnight** [comment]
I'd definitely love to write articles on this subject! I only need extra time for this :)
